spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srikanth?user=root&password=
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
