spring:
  datasource:
    url: jdbc:mysql://localhost:3306/srikanth?user=root&password=nsr@6321
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  application:
    name: login-service

server:
  port: 8082
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    serviceUrl: 
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
